# docker-compose.yml

version: "3.9"

# Basic service template
x-template: &basic-container
  image: node:20
  volumes:
    - /home/koshkindom/app/report:/home/report
  env_file: .env
  working_dir: /home
  command:
    - bash
    - -c
    - |
      rm -rf crypto-bot-surfer && \
      git clone --branch signal-trading https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run nodemon

# Creating containers
services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  external-signals--1h:
    container_name: crypto-bot-surfer-1
    <<: *basic-container
    environment:
      - INDICATOR=external
      - HEARTBEAT_INTERVAL=1h
      - NEXT_TRADE_DELAY=1h
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=trades-external-1h.csv

  pump--15m:
    container_name: crypto-bot-surfer-2
    <<: *basic-container
    environment:
      - INDICATOR=pump
      - HEARTBEAT_INTERVAL=15m
      - NEXT_TRADE_DELAY=1m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=trades-pump-15m.csv

  dump--15m:
    container_name: crypto-bot-surfer-3
    <<: *basic-container
    environment:
      - INDICATOR=dump
      - HEARTBEAT_INTERVAL=15m
      - NEXT_TRADE_DELAY=1m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=trades-dump-15m.csv

  flat--15m:
    container_name: crypto-bot-surfer-4
    <<: *basic-container
    environment:
      - INDICATOR=flat
      - HEARTBEAT_INTERVAL=15m
      - NEXT_TRADE_DELAY=1m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=trades-flat-15m.csv
