# docker-compose.yml

version: "3.9"

# Basic service template
x-template: &basic-container
  depends_on:
    queue:
      condition: service_healthy
  image: node:20
  volumes:
    - /home/koshkindom/report:/report
  env_file: .env
  working_dir: /home/koshkindom/app
  command:
    - bash
    - -c
    - |
      git clone --branch signal-trading https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run nodemon

# Creating containers
services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  external-signals--01m:
    container_name: crypto-bot-surfer
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=01m
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/koshkindom
      - REPORT_FILE_NAME=trades-01m
