# docker-compose.override.yml

version: "3.9"

# Basic service template
x-template: &basic-container
  depends_on:
    queue:
      condition: service_healthy
  image: node:14
  volumes:
    - /report:/home/_report
  env_file: .env
  working_dir: /home
  command:
    - bash
    - -c
    - |
      git clone https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run report

# Creating containers
services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  simple--01m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=01m
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_NAME=simple--01m

  simple--02m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=02m
      - NEXT_TRADE_DELAY=02m
      - REPORT_FILE_NAME=simple--02m

  simple--03m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=03m
      - NEXT_TRADE_DELAY=03m
      - REPORT_FILE_NAME=simple--03m

  simple--04m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=04m
      - NEXT_TRADE_DELAY=04m
      - REPORT_FILE_NAME=simple--04m

  simple--05m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=05m
      - NEXT_TRADE_DELAY=05m
      - REPORT_FILE_NAME=simple--05m

  simple--06m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=06m
      - NEXT_TRADE_DELAY=06m
      - REPORT_FILE_NAME=simple--06m

  simple--07m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=07m
      - NEXT_TRADE_DELAY=07m
      - REPORT_FILE_NAME=simple--07m

  simple--08m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=08m
      - NEXT_TRADE_DELAY=08m
      - REPORT_FILE_NAME=simple--08m

  simple--09m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=09m
      - NEXT_TRADE_DELAY=09m
      - REPORT_FILE_NAME=simple--09m

  simple--10m:
    <<: *basic-container
    environment:
      - INDICATOR=simple
      - HEARTBEAT_INTERVAL=10m
      - NEXT_TRADE_DELAY=10m
      - REPORT_FILE_NAME=simple--10m

  simple--11m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=11m
      - NEXT_TRADE_DELAY=11m
      - REPORT_FILE_NAME=simple--11m

  simple--12m:
    <<: *basic-container
    environment:
      - HEARTBEAT_INTERVAL=12m
      - NEXT_TRADE_DELAY=12m
      - REPORT_FILE_NAME=simple--12m
