# docker-compose.yml

# Basic service template
x-template: &basic-container
  image: node:20
  volumes:
    - /home/report:/home/report
  env_file: .env
  working_dir: /home
  command:
    - bash
    - -c
    - |
      rm -rf crypto-bot-surfer && \
      git clone --branch signal-trading https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run nodemon

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  psar--5m-fast-1:
    container_name: crypto-bot-surfer-1
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=BTC
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-1.csv

  psar--5m-fast-2:
    container_name: crypto-bot-surfer-2
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=BNB
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-2.csv

  psar--5m-fast-3:
    container_name: crypto-bot-surfer-3
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=XRP
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-3.csv

  psar--5m-fast-4:
    container_name: crypto-bot-surfer-4
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=DOGE
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-4.csv

  psar--5m-fast-5:
    container_name: crypto-bot-surfer-5
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=CAKE
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-5.csv

  psar--5m-fast-6:
    container_name: crypto-bot-surfer-6
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=TON
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-6.csv

  psar--5m-fast-7:
    container_name: crypto-bot-surfer-7
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=ADA
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-7.csv

  psar--5m-fast-8:
    container_name: crypto-bot-surfer-8
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - HEARTBEAT_INTERVAL=5m
      - PRYMARY_SYMBOL=DOT
      - BACKTEST_PERIODS=500
      - NEXT_TRADE_DELAY=01m
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-fast-05m-8.csv
