# docker-compose.yml

# Basic service template
x-template: &basic-container
  image: node:20
  volumes:
    - /home/report:/home/report
  env_file: .env
  working_dir: /home
  command:
    - bash
    - -c
    - |
      rm -rf crypto-bot-surfer && \
      git clone --branch signal-trading https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run nodemon

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  crypto-bot-surfer-1:
    container_name: crypto-bot-surfer-1
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=BTC
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-BTC.csv

  crypto-bot-surfer-2:
    container_name: crypto-bot-surfer-2
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=ETH
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-ETH.csv

  crypto-bot-surfer-3:
    container_name: crypto-bot-surfer-3
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=BNB
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-BNB.csv

  crypto-bot-surfer-4:
    container_name: crypto-bot-surfer-4
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=XRP
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-XRP.csv

  crypto-bot-surfer-5:
    container_name: crypto-bot-surfer-5
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=DOGE
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-DOGE.csv

  crypto-bot-surfer-6:
    container_name: crypto-bot-surfer-6
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=ADA
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-ADA.csv

  crypto-bot-surfer-7:
    container_name: crypto-bot-surfer-7
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=SOL
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-SOL.csv

  crypto-bot-surfer-8:
    container_name: crypto-bot-surfer-10
    <<: *basic-container
    environment:
      - INDICATOR=psar
      - PRIMARY_SYMBOL=DOT
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=psar-1m-DOT.csv
