# docker-compose.yml

# Basic service template
x-template: &basic-container
  image: node:20
  volumes:
    - /home/report:/home/report
  env_file: .env
  working_dir: /home
  command:
    - bash
    - -c
    - |
      rm -rf crypto-bot-surfer && \
      git clone --branch signal-trading https://github.com/digitalfuture/crypto-bot-surfer.git && \
      cd crypto-bot-surfer && \
      npm install && \
      npm run nodemon

services:
  # # # # # # # # # # # # # # # # # # # # # # # # # # #

  crypto-bot-surfer-1:
    container_name: crypto-bot-surfer-1
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=1
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-1.csv

  crypto-bot-surfer-2:
    container_name: crypto-bot-surfer-2
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=2
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-2.csv

  crypto-bot-surfer-3:
    container_name: crypto-bot-surfer-3
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=3
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-3.csv

  crypto-bot-surfer-4:
    container_name: crypto-bot-surfer-4
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=4
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-4.csv

  crypto-bot-surfer-5:
    container_name: crypto-bot-surfer-5
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=5
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-5.csv

  crypto-bot-surfer-6:
    container_name: crypto-bot-surfer-6
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=6
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-6.csv

  crypto-bot-surfer-7:
    container_name: crypto-bot-surfer-7
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=7
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-7.csv

  crypto-bot-surfer-8:
    container_name: crypto-bot-surfer-8
    <<: *basic-container
    environment:
      - SYSTEM_PARAM_1=6
      - SYSTEM_PARAM_2=8
      - REPORT_FILE_DIR=/home/report
      - REPORT_FILE_NAME=pump-15m-8.csv
